import type { Metadata } from 'next'
import '@/libs/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={`antialiased`}>
      <body>{children}</body>
    </html>
  )
}
